# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Vite App with CDK (build and deploy)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install
        run: npm install

      - name: Build
        run: |
          npm run build
        env:
          NODE_ENV: production
          REACT_APP_VERSION: v0.1.${{ github.run_number }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-build-with-infra
          path: |
            dist
            infra
          if-no-files-found: error

  deploy-to-dev:
    name: deploy to dev environment
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "dev"
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app-build-with-infra

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws configure set aws_secret_access_key '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws configure set region 'us-east-1'

      - name: Get caller identity
        run: aws sts get-caller-identity
        
      - name: Install
        run: npm install
        working-directory: infra

      - name: Build
        run: npm run build
        working-directory: infra

      - name: Synthesize
        run: npm run cdk:synth
        working-directory: infra

      - name: Provision & Deploy 
        run: npm run cdk:deploy
        working-directory: infra
